"""size text fix

Revision ID: a78abd91480d
Revises: a1de702391a1
Create Date: 2025-02-26 13:39:53.919465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a78abd91480d'
down_revision = 'a1de702391a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.alter_column('ai_plot',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('ai_characters',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('ai_moment',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('ai_idea',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('ai_impress',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=3000),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=3000),
               existing_nullable=False)

    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.alter_column('ai_impress',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
        batch_op.alter_column('ai_idea',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
        batch_op.alter_column('ai_moment',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
        batch_op.alter_column('ai_characters',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
        batch_op.alter_column('ai_plot',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###
